### ISSUE TITLE
Deprecate/archive old ec2-hibernate-linux-agent repo

### ISSUE THREAD

**Issue by maresb** [aws/amazon-ec2-hibinit-agent#19]
The [ec2-hibernate-linux-agent](https://github.com/aws/ec2-hibernate-linux-agent) repository seems to contain an old version of this project. Also, the Ubuntu 20.04 AMI seems to have the old `hibagent` and this `hibinit-agent` both preinstalled. It's really confusing.

**Comment by stewartsmith** [comment]
Rather confusingly, the other (allegedly) deprecated repository has a bunch of commits since this issue was opened.

Version number wise, the deprecated repository seems to say 1.1.x which is greater than the 1.0.x that this, the non-deprecated repository has?

I'm confused.

**Comment by thimslugga** [comment]
@stewartsmith

https://github.com/aws/ec2-hibernate-linux-agent is the agent used for spot instance hibernation

https://github.com/aws/amazon-ec2-hibinit-agent is the agent used for on-demand instance hibernation

**Comment by stewartsmith** [comment]
This seems..... unclear to say the least.

**Comment by kjeffsh** [comment]
The [ec2-hibernate-linux-agent](https://github.com/aws/ec2-hibernate-linux-agent) has now been archived for clarity, and Readme has been updated to explicitly state it's legacy status.

Hopefully this should clear up any confusion in future. 
Thanks @thimslugga @stewartsmith @maresb for bringing up this issue.
