### ISSUE TITLE
Fails with "Not enough swap space for hibernation"

### ISSUE THREAD

**Issue by maresb** [aws/amazon-ec2-hibinit-agent#20]
When trying to hibernate an Ubuntu EC2 instance (either through the console or [with this procedure](https://stackoverflow.com/a/69818248)), I'm getting the error

```text
Failed to hibernate system via logind: Not enough swap space for hibernation
```

Looking into the logs with `sudo journalctl -u systemd-logind`, I see

```text
/swapfile: is a candidate device.
/swap-hibinit: ignoring device with lower priority
No swap partitions or files matching resume config were found in /proc/swaps.
```

Running `sudo cat /proc/swaps` I see

```text
Filename				Type		Size		Used		Priority
/swapfile                               file		4194300		0		-2
/swap-hibinit                           file		4095996		0		-3
```

so that the `/swapfile` which I created has higher priority than the `/swap-hibinit` file (managed by the Ubuntu-patched hibinit-agent) which is referenced in the grub settings.

Perhaps the priority needs to be set in the `swapon` command?

**Comment by chenxiaoyi** [comment]
Does `/swapfile` have enough space? Trying to understand the issue better, were these two files created by this agent?

**Comment by maresb** [comment]
I created `/swapfile` and the agent created `/swap-hibinit`. (Ubuntu patches `hibinit-agent` to rename `/swap` to `/swap-hibinit`.) If I remember correctly, hibernation ignores everything but the swapfile with highest priority (in this case my `/swap`, which is indeed big enough). I think it fails because `/swap-hibinit` is registered with grub. When it tries to hibernate, it notices the mismatch and fails.

Increasing the priority solves the problem. (See my PR.)

**Comment by matthewruffell** [comment]
Hello @maresb thanks for reporting the issue!

We are tracking it downstream in Ubuntu at [LP#1968805](https://bugs.launchpad.net/ubuntu/+source/ec2-hibinit-agent/+bug/1968805), and I hope to get this fixed up soon.

I made a new patch using your same idea, just changing the priority to the maximum 32767, which is more robust to priorities users could be using out in the wild.

Thanks,
Matthew

**Comment by maresb** [comment]
Thanks so much @matthewruffell for moving this forward!!! I like your patch and I marked the linked issues as "this bug affects me"

**Comment by eptiger** [comment]
Thanks for reporting and putting together a patch - the engineering team in EC2 that maintains the agent is aware of the patch and are prioritizing testing it. I'll ask them to give you an ETA when they have one.

**Comment by xiongxia-aws** [comment]
The pull request was approved and the commit is merged(https://github.com/aws/amazon-ec2-hibinit-agent/commit/02245366eeaf032e86731cbb20b39e4621c95fbb). Closing the issue.
