### ISSUE TITLE
hibinit-agent lacks fs checks and uses fallocate to create swapfiles

### ISSUE THREAD

**Issue by thimslugga** [aws/amazon-ec2-hibinit-agent#25]
It looks like the hibinit-agent is currently not doing any checks to determine the underlying filesystem and it uses fallocate when creating swapfiles.

https://github.com/aws/amazon-ec2-hibinit-agent/blob/02245366eeaf032e86731cbb20b39e4621c95fbb/agent/hibinit-agent#L65

https://github.com/aws/amazon-ec2-hibinit-agent/blob/02245366eeaf032e86731cbb20b39e4621c95fbb/agent/hibinit-agent#L192

It's best to use dd or something other than fallocate for creating swapfiles. There should also be checks to determine the backing filesystem and possibly kernel version as not all file systems (also depends on kernel version/backports) support swapfiles. 

https://man.archlinux.org/man/swapon.8#Files_with_holes

https://unix.stackexchange.com/questions/518559/what-are-the-holes-in-files-created-with-fallocate

https://btrfs.readthedocs.io/en/latest/Swapfile.html?highlight=swap%20files

https://bugzilla.redhat.com/show_bug.cgi?id=1129205

https://manpages.ubuntu.com/manpages/xenial/en/man8/mkswap.8.html
```
Note that a swap file must not contain any holes. Using cp to create the file  is  not acceptable.
Neither  is  use  of  fallocate on file systems that support preallocated files, such as XFS or
ext4, or on copy-on-write filesystems like btrfs.  It is recommended to use dd and /dev/zero in 
these cases.  Please read notes from swapon before adding a swap file to copy-on-write 
filesystems.
```
https://manpages.ubuntu.com/manpages/jammy/en/man8/swapon.8.html
```
Files with holes

The swap file implementation in the kernel expects to be able to write to the file directly, 
without the assistance of the filesystem. This is a problem on files with holes or on copy-on-
write files on filesystems like Btrfs.

Commands like cp or truncate create files with holes. These files will be rejected by swapon.

Preallocated files created by fallocate may be interpreted as files with holes too depending of 
the filesystem. Preallocated swap files are supported on XFS since Linux 4.18.

The most portable solution to create a swap file is to use dd and /dev/zero.

Btrfs

Swap files on Btrfs are supported since Linux 5.0 on files with nocow attribute. See the 
btrfs manual page for more details.
```

**Comment by kjeffsh** [comment]
Hey Adam, thanks for the note!
We've pushed a new commit to [3e9b424](https://github.com/aws/amazon-ec2-hibinit-agent/commit/3e9b424e02a335dacdf5ec86ed2ef3c9e517a677) to address the btrfs issue.

I do agree that dd if=/dev/zero would be a good catch all alternative to using fallocate. However, the runtime for dd is less scalable for larger memory sizes. For OSs that require filling holes, we have a functionality to fill holes enabled by   touch-swap=True.

If you see any issues with this, please leave us a reply!
If not, we'll be closing out this issue in the next week
