### ISSUE TITLE
Amazon Linux 2 requires `pm-utils` package to hibernate

### ISSUE THREAD

**Issue by yoshifumi-kinoshita** [aws/amazon-ec2-hibinit-agent#26]
When you install `ec2-hibinit-agent` to amzn2-ami-minimal, EC2 Hibernation doesn't work as expected.

### Repro steps:
1. Create instance with the following configuration
- Region: us-west-2
- AMI: ami-09db9da37d31787f3 (amzn2-ami-minimal-hvm-2.0.20220606.1-x86_64-ebs)
- Instance Type: t3.micro
- EBS: 30GB gp2, Encrypted
- Stop - Hibernate behavior: Enable

2. Install `ec2-hibinit-agent`
```
  $ sudo yum update -y
  $ sudo yum install ec2-hibinit-agent -y
```

3. Reboot
```
  $ sudo reboot
```

4. Hibernate the instance from Management console

### Expected result:
The instance successfully hibernate.
We expect the following messages in /var/log/messages.
~~~
Jan  8 21:56:54 ip-172-31-1-206 kernel: PM: hibernation entry
...
Jan  8 21:56:54 ip-172-31-1-206 kernel: PM: hibernation exit
~~~

### Actual result:
The instance keeps running.
You might see the following log in /var/log/messages.
~~~
Jan  8 21:44:22 ip-172-31-1-206 root: Hibernation failed, Sleeping 2 mins before retry
~~~

### Note
Looking at /etc/acpi/actions/sleep.sh, it apparently depends on `/usr/sbin/pm-hibernate` included in `pm-utils` package.
( https://github.com/aws/amazon-ec2-hibinit-agent/blob/master/acpid.sleep.sh#L13 )
~~~
        swapon --priority=$swap_priority /swap && /usr/sbin/pm-hibernate
~~~

If you install `pm-utils`, hibernation works as expected.
~~~
$ sudo yum install pm-utils
~~~

**Comment by kjeffsh** [comment]
Issue resolved in https://github.com/aws/amazon-ec2-hibinit-agent/commit/8ec340e71de2f4dbf38233fc295cf30cfd5dae32
