### ISSUE TITLE
Ubuntu 22.04 incorrect installation

### ISSUE THREAD

**Issue by phipps73** [aws/amazon-ec2-hibinit-agent#30]
Have just created a new EC2 instance with AMI image: ubuntu/images/hvm-ssd/ubuntu-jammy-22.04-amd64-server-20230516 with a 48gb EBS volume and I have noticed that the root directory contains the following folder structure:

> "
    > var
        > lib
           > hibinit-agent"

The top level folder (at same level as boot, dev, etc, home...) is a double quote with a var folder within and so on.

Firstly, am I safe to delete this?
Secondly, how do I reinstall hibinit-agent as it isn't in the directory where I presume from above it should, namely, /var/lib/

**Comment by secarola** [comment]
This bug has been resolved with this patch: https://git.launchpad.net/ubuntu/+source/ec2-hibinit-agent/commit/?h=applied/ubuntu/jammy-devel&id=85b739e783725bce2206429bb20380c6d81b8be1. Resolving this issue, please feel free to reopen if anything else comes up.

**Comment by secarola** [comment]
This bug has been resolved with this patch: https://git.launchpad.net/ubuntu/+source/ec2-hibinit-agent/commit/?h=applied/ubuntu/jammy-devel&id=85b739e783725bce2206429bb20380c6d81b8be1. Resolving this issue, please feel free to reopen if anything else comes up.
