### ISSUE TITLE
percentage-of-ram and target-size-mb not working as expected

### ISSUE THREAD

**Issue by judouk** [aws/amazon-ec2-hibinit-agent#47]
I am using a Rocky8 installation on an AWS EC2 m5a.large instance
I have ec2-hibinit-agent-1.0.9-1.el8.noarch installed

My /etc/hibinit-config.cfg contains
```
[swap]
# If there's no swap then we create it to be equal to the specified
# percentage of RAM or to the target size, whichever is greater
percentage-of-ram = 100
target-size-mb = 4000
```

My host has 8GB installed but the swap file is created as 4GB
```
# free -m
              total        used        free      shared  buff/cache   available
Mem:           7536         580        5723          11        1232        6700
Swap:             0           0           0

# ls -l /swap
-rw-------. 1 root root 4194304000 Aug 28 16:44 /swap
```

Looking at the logs, it seems to contradict itself. I need 7912648704....so I allocate 4194304000 !!!

```
Aug 28 16:50:59 workstation /hibinit-agent[29654]: Will check if swap is at least: 7536 megabytes
Aug 28 16:50:59 workstation /hibinit-agent[29654]: There's enough space (97088696320 present, 7912648704 needed) for the swap file on the device: /
Aug 28 16:50:59 workstation /hibinit-agent[29654]: Allocating 4194304000 bytes in /swap
```

For now, I've updated my configuration to use target-size-mb = 8192 but this feels like a bug

**Comment by deborshi1988** [comment]
As provided in the  comment of /etc/hibinit-config.cfg , we take into account which one is greater. 

For your configuration , the percentage-of-ram = 100  was provided ,  so we have gone ahead with validating . 

But you are correct in pointing out that there is an inconsistency. We should be allocating the same size as we are validating. We will track this issue.

**Comment by dhs-rec** [comment]
@JarredTD, why has this been closed? This is obviously a bug in 1.0.9. It always creates a swap file with size `target-size-mb`, even if the size calculated from `percentage-of-ram` is (much) larger. And the reason for this is here:
```
    245 class SwapInitializer(object):
    246     def __init__(self, config):
    247         self.swap_size = config.swap_mb * KB * KB    # <=== swap size is set to swap_mb, regardless of percentage setting
    248         self.config = config
    249         self.block_size = KB * KB  # 1 MiB
    250 
...
    272     def do_allocate(self):
    273         print_to_sys_log("Allocating %d bytes in %s" % (self.swap_size, SWAP_FILE))
    274         with open(SWAP_FILE, 'w+') as fl:
    275             fallocate(fl, self.swap_size)
    276         os.chmod(SWAP_FILE, 0o600)  # Read + Write Permissions
```
Alas, it even recognizes a too small swap file upon restart, throws it away, and creates a too small file again:
```
Jul 16 12:46:21 hostname hibinit-agent[22000]: Will check if swap is at least: 31551 megabytes
Jul 16 12:46:21 hostname hibinit-agent[22000]: Swap already exists! (have 4194304000, need 33084051456), deleting existing swap file /swap-hibinit
Jul 16 12:46:21 hostname hibinit-agent[22000]: There's enough space (249512062976 present, 33094537216 needed) for the swap file on the device: /
Jul 16 12:46:21 hostname hibinit-agent[22000]: Allocating 4194304000 bytes in /swap-hibinit
Jul 16 12:46:21 hostname hibinit-agent[22000]: Swap pre-heating is skipped, the swap blocks won't be touched during to ensure they are ready
Jul 16 12:46:21 hostname hibinit-agent[22000]: Running: mkswap /swap-hibinit
Jul 16 12:46:21 hostname hibinit-agent[22024]: Setting up swapspace version 1, size = 3.9 GiB (4194299904 bytes)
```
Please reopen, and fix.

**Comment by dhs-rec** [comment]
> As provided in the comment of /etc/hibinit-config.cfg , we take into account which one is greater.

@deborshi1988, yes, the comment says so, but the code doesn't follow.

**Comment by dhs-rec** [comment]
For those who also stumble across this, here's a workaround:

1. Restart the agent, and look at the log
2. Copy the value behind `need` (see log excerpt from my previous comment)
3. Remove the current (too small) `/swap-hibinit` file
4. Recreate it with `fallocate -l <needed size> /swap-hibinit`
5. Make is a swap file: `mkswap /swap-hibinit`
6. Restart the agent again, it should now report `There's sufficient swap available`

**Comment by JarredTD** [comment]
This issue was resolved in [this](https://github.com/aws/amazon-ec2-hibinit-agent/commit/3700a58fb73778dd02d37617b952766d4828e332) commit. The latest release includes this commit (1.0.9-1).

**Comment by dhs-rec** [comment]
Thanks for releasing the fix. BTW: Would have been better to name it 1.0.10, since the `-1` is usually used by distributions to mark changes in packaging (see above: `ec2-hibinit-agent-1.0.9-1.el8.noarch`).
